### ISSUE TITLE
Failed to execute goal ...

### ISSUE THREAD

**Issue by Addlai** [springhow/springboot-pdf-demo#1]
I'm new to Spring. 
Is it expected that this will compile on a current java development system?
When I attempt to build with 
mvn package
I get
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project pdf-demo: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x4674d90) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x4674d90

Is that expected?

**Comment by raja-anbazhagan** [comment]
In newer java versions, the internal `com.sun` packages are not available for public access. As the Lombok plugin depends on this package, you are getting this error. 
You can easily solve this problem in two ways.
1. Upgrade Spring Boot to a more recent version (currently 2.5.4)
2. Use Java 8
